### PR TITLE
Making the output prettier

### PR DESCRIPTION
**Pull request by timeopochin**
This is pretty much what the title says it is, this is all aesthetics, there are no changes to the algorithm
Let me know if you like it :smiley:

Also I don't know how to deal with many branches yet, this is branched off my other pull request so I'm not sure how all of that works. I'm guessing the other needs to be merged first, or maybe it should be closed and this one should be merged because it also as the commits from the other one.

I also totally get it if you do not want to merge this

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
1. I love it, it looks really professional!
2. (I also really like that you added type-information to each function-parameter)

> Also I don't know how to deal with many branches yet, this is branched off my other pull request so I'm not sure how all of that works.

I think the way it's usually handled is to not base branches off of each other, but base everything off of main. I'm not 100% sure myself, though.

> I'm guessing the other needs to be merged first, or maybe it should be closed and this one should be merged because it also as the commits from the other one.

Yes, let's first work on the AUTO_LAYER-branch, and then inspect this PR more closely!

Have you tested whether this also works on Windows?

**Comment by timeopochin** [comment]
> Have you tested whether this also works on Windows?

I have not, I will have access to a Windows machine on monday. There's no reason why it shouldn't work but it is worth checking before merging.

Though now that you mention this I'm thinking a `USE_UNICODE_FOR_UI` option could be good too, to avoid things looking like `▯▯▯` or worse if the teminal doesn't support Unicode.

I used ANSI escape codes, a quick Google tells me that they are supported by `conhost.exe` and `cmd` starting from Windows 10 TH2 (v1511), though [they have to be enabled](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN)

**Comment by Glitchy-Tozier** [comment]
Okay, so for this PR to pass, the main to-dos I can think of are:

1. Update this PR to use the latest-version of the branch it's based on
2. Test on Windows, just to make sure
3. You did a great job with adding type-hints to the functions' parameters. Please also add return-types where data is returned
4. Please add doc-comments to all functions & classes.
Make them as detailed as possible, describing:
    - what they do & what they're used for
    - what data they return (if they return something),
    - and potentially even mention the default-parameter-values (if there are any defaults).

Overall, I am impressed with this code! Did you use this before and copy it over or did you write all of this from scratch, just for this PR?

**Comment by timeopochin** [comment]
> Did you use this before and copy it over or did you write all of this from scratch, just for this PR?

I wrote it from scratch just for the PR!

And okay, those seem like good guidelines. I will look at fixing/redoing this PR in a couple days

**Comment by timeopochin** [comment]
Fixed all conflicts and made some improvements in #7

**Pull request closed without merging**
