### PR TITLE
Making the output prettier

### PR DESCRIPTION
**Pull request by timeopochin**
This should be better :smiley:

Let me know if anything need changes.

### CODE REVIEW

**Comment by Glitchy-Tozier** [comment]
I see you've improved on a couple of things. I had a hard time finding things to complain about!

At the moment I don't have access to my PC, I should be able to review the PR on tuesday.

A few small things I noticed when reading the code:

1. ~Are you sure this is okay? I don't fully remember that part of the code, but I was under the impression that this variable needed to be global.~
~EDIT: On closer inspection, we probably could straight-up replace `asciiReplacementChars` with `ASCII_REPLACEMENT_CHARS` inside the `asciify(…)`-function.~



2. Is this some formatting standard? I actually liked the way the function previously looked 🤔



3. If there are classes that aren't supposed to get used in any other files except in `ui.py`, it might be a good idea to make those classes / standalone-functions private (`Cursor`, for example?).
You'll have to look up how to do so, I think it's either single or double underscores before the Class-/function-name.

**Comment by Glitchy-Tozier** [comment]
I have made some small but important changes & fixes to the original code, I recommend taking a look at them to get an understanding of the merge-conflicts.
(One of the fixes was related to the AUTO_LAYER-feature, by the way)

In addition to…
1. my suggestions above and
2. resolving the merge-conflicts,

…please return to using explicit `import`-statements instead of `import *`. The reason for this request is that while this may be ugly code, it is the only way I found of letting the IDE assist in navigating to different files easily by clicking a variable.

**Comment by Glitchy-Tozier** [comment]
Also, due to the most recent changes, please remove the line `asciiReplacementChars = ASCII_REPLACEMENT_CHARS` from `def asciify(…)`, as it now is required to be placed outside that function (see https://github.com/Glitchy-Tozier/8vim_keyboard_layout_calculator/commit/093a4328e0f4dbb912af42afedbab3eac71bdb19)

**Comment by Glitchy-Tozier** [comment]
How's it going? :)
Are you still interested in this PR?

**Comment by timeopochin** [comment]
Hello, I am still interested, but I've just started my university course and my free time is non-existant for the time being, we can close the PR and I will open a new one if I find the time in the future

**Comment by Glitchy-Tozier** [comment]
In that case I'll be resolving the conflicts and merging the PR myself, it's too good to pass up on.
Good luck with your studies, I'm always open for new PRs. :)

**Pull request merged**
